### ISSUE TITLE
Сбой при загрузки системы

### ISSUE THREAD

**Issue by runnerfanspb** [AlexxIT/StartTime#2]
Добрый день. После обновления компонента, система уходит в перезагрузку и далее не загружается. 
С чем это может быть связано?

**Comment by runnerfanspb** [comment]
проверил. еще раз.
из всех компонентов при обновлении данной интеграции идет вис системы. и только при обновлении на последнюю версию

**Comment by BrownC0de** [comment]
Аналогично

**Comment by Romandvd** [comment]
Подтверждаю ХА не загружается не на 2021.6.3 и на 2021.6.4 с последней вашей версией. Пока не удалить аддон.

**Comment by AlexxIT** [comment]
У меня не повторяется на основном и тестовом сервере. Нужны подробности

**Comment by Romandvd** [comment]
Дружище сервер ubuntu в виртулке, работает уже 3 года. На версии 1.1.6 не загружается ХА. Только удаляю твою интеграцию и сразу загружается. Перезапускаю через portainer сам home assistant. Версия 1.1.4 всё работает...

**Comment by Romandvd** [comment]
Какая ещё инфа нужна?

**Comment by varrcan** [comment]
```
2021-07-14 22:08:33 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 322, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 314, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 108, in run
    return asyncio.run(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/src/homeassistant/homeassistant/runner.py", line 94, in setup_and_run_hass
    hass = await bootstrap.async_setup_hass(runtime_config)
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 129, in async_setup_hass
    await async_from_config_dict(config_dict, hass) is not None
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 242, in async_from_config_dict
    _LOGGER.info("Home Assistant initialized in %.2fs", stop - start)
  File "/config/custom_components/start_time/sensor.py", line 28, in monkey_info
    self.internal_update(args[0])
  File "/config/custom_components/start_time/sensor.py", line 63, in internal_update
    setup_time: dict = self.hass.data.get('setup_time')
AttributeError: 'NoneType' object has no attribute 'data'
```

Система вешается через секунд 20 после перезагрузки ХА


## System Health

version | core-2021.7.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.4.0-77-generic
arch | x86_64
timezone | Europe/Moscow

**Comment by varrcan** [comment]
Проблема сама собой не решилась ))

`2021-08-15 22:14:45 ERROR (MainThread) [homeassistant.components.sensor] The start_time platform for the sensor integration does not support platform setup. Please remove it from your config.`

**Comment by varrcan** [comment]
В общем, работает, если активировать через гуй, из yaml выдаёт ошибку

**Comment by AlexxIT** [comment]
Probably no longer relevant
