### ISSUE TITLE
Incompatibility with HA 2024.3.0b0

### ISSUE THREAD

**Issue by FrancoLoco** [AlexxIT/StartTime#3]
I had to remove the component because HA would hang on boot when loading this custom_component. After removing it, it boots fine.

**Comment by drthanwho** [comment]
This is the actual error
```
2024-03-05 11:27:55.603 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 221, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/runner.py", line 188, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in setup_and_run_hass
    hass = await bootstrap.async_setup_hass(runtime_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 230, in async_setup_hass
    await async_from_config_dict(config_dict, hass) is not None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 384, in async_from_config_dict
    _LOGGER.info("Home Assistant initialized in %.2fs", stop - start)
  File "/config/custom_components/start_time/sensor.py", line 28, in monkey_info
    self.internal_update(args[0])
  File "/config/custom_components/start_time/sensor.py", line 67, in internal_update
    for integration, timedelta in sorted(
                                  ^^^^^^^
  File "/config/custom_components/start_time/sensor.py", line 69, in <lambda>
    key=lambda kv: kv[1].total_seconds(),
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'total_seconds'
```

**Comment by johntdyer** [comment]
FYI, it seems this was added to the block list https://github.com/home-assistant/core/pull/112481

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/StartTime/releases/tag/v1.1.7

**Comment by AlexxIT** [comment]
@johntdyer thanks for info
