### ISSUE TITLE
Deprecated async_forward_entry_setup call

### ISSUE THREAD

**Issue by tjorim** [AlexxIT/StartTime#7]
This will stop working in HA 2025.6

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 11:45:31 (11 occurrences)
Last logged: 11:46:21

Detected that custom integration 'start_time' calls async_forward_entry_setup for integration, start_time with title: Start Time and entry_id: 4042dae57affa7b941c965a433878efb, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/start_time/__init__.py, line 18: hass.async_create_task(hass.config_entries.async_forward_entry_setup(, please create a bug report at https://github.com/AlexxIT/StartTime/issues
```

**Comment by qosmio** [comment]
FYI,

Opened a PR for this issue here:
[fix deprecated async_forward_entry_setup call](https://github.com/AlexxIT/StartTime/pull/8)

**Comment by victorclaessen** [comment]
I have this issue now after upgrading to HA2025.6. Could you please accept the PR if that works?

**Comment by Blacksli** [comment]
2025.6.1

> Log details (WARNING)
> This error originated from a custom integration.
> Logger: custom_components.start_time.sensor
> Source: custom_components/start_time/sensor.py:35
> integration: Start Time ([documentation](https://github.com/AlexxIT/StartTime), [issues](https://github.com/AlexxIT/StartTime/issues))
> First occurred: 15:16:30 (1 occurrence)
> Last logged: 15:16:30
> 
> update error
> Traceback (most recent call last):
>   File "/config/custom_components/start_time/sensor.py", line 35, in monkey_info
>     self.internal_update(args[0])
>     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
>   File "/config/custom_components/start_time/sensor.py", line 44, in internal_update
>     setup_time: dict = self.hass.data.get("setup_time")
>                        ^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute data
> 
>

**Comment by WBrown15** [comment]
same issue here, since last update to 
Installationsmethode
Home Assistant OS
Core
2025.6.1
Supervisor
2025.05.5
Operating System
15.2
Frontend
20250531.3

**Comment by 0kinawa** [comment]
Регистратор: homeassistant.config_entries
Источник: config_entries.py:749
Зафиксировано первый раз: 18 июня 2025 г. в 23:52:02 (1 случай)
Зафиксировано последний раз: 18 июня 2025 г. в 23:52:02

Error setting up entry Start Time for start_time
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/start_time/__init__.py", line 18, in async_setup_entry
    hass.async_create_task(hass.config_entries.async_forward_entry_setup(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by beliy1985** [comment]
+++

**Comment by bcutter** [comment]
@AlexxIT what about the PR(s) fixing this?
